import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
// import '@/styles/globals.css';
import '@workspace/ui/globals.css';
import { MSWProvider } from '@/components/provider/msw-provider';
import { AppSidebar } from '@workspace/ui/components/sidebar/app-sidebar';
import { ColorThemeProvider } from '@/components/provider/color-theme-provider';
import { SidebarProvider } from '@/components/provider/sidebar-provider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MSWProvider>
          <ColorThemeProvider>
            <SidebarProvider>{children}</SidebarProvider>
          </ColorThemeProvider>
        </MSWProvider>
      </body>
    </html>
  );
}
